name: Run Lab2Dev Automation

on:
#  schedule:
#    - cron: '0 6 * * *'  # Executa diariamente às 06:00 UTC
  workflow_dispatch:
    inputs:
      START_DATE:
        description: 'Data de início do apontamento (Formato: DD/MM/YYYY)'
        required: false
        default: ''
      END_DATE:
        description: 'Data de fim do apontamento (Formato: DD/MM/YYYY)'
        required: false
        default: ''
      WORK_START_TIME:
        description: 'Horário de início do expediente (Formato: HH:MM:SS)'
        required: false
        default: '09:00:00'
      WORK_END_TIME:
        description: 'Horário de fim do expediente (Formato: HH:MM:SS)'
        required: false
        default: '17:00:00'
      DESCRIPTION:
        description: 'Descrição da atividade'
        required: false
        default: 'Atividades SRE/DevOps'

jobs:
  run-lab2dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script principal
        env:
          LAB2DEV_USER_EMAIL: ${{ secrets.LAB2DEV_USER_EMAIL }}
          LAB2DEV_USER_PASSWORD: ${{ secrets.LAB2DEV_USER_PASSWORD }}
          START_DATE: ${{ github.event.inputs.START_DATE || '' }}
          END_DATE: ${{ github.event.inputs.END_DATE || '' }}
          WORK_START_TIME: ${{ github.event.inputs.WORK_START_TIME || '09:00:00' }}
          WORK_END_TIME: ${{ github.event.inputs.WORK_END_TIME || '17:00:00' }}
          DESCRIPTION: ${{ github.event.inputs.DESCRIPTION || 'Atividades SRE/DevOps' }}
        run: python main.py
